### ISSUE TITLE
Error Aot

### ISSUE THREAD

**Issue by rbonillajr** [johnpapa/angular2-go#35]
$ npm run start-aot

> angular2-go@0.0.1 start-aot D:\jscode\a2-go
> npm run aot && npm run rollup && gulp copy-aot && npm run lite

> angular2-go@0.0.1 aot D:\jscode\a2-go
> ngc -p tsconfig-aot.json

Error: Error File 'D:/jscode/a2-go/typings/index.d.ts' not found.
    at Object.check (D:\jscode\a2-go\node_modules\@angular\compiler-cli\node_mod                                                               ules\@angular\tsc-wrapped\src\tsc.js:31:15)
    at Object.main (D:\jscode\a2-go\node_modules\@angular\compiler-cli\node_modu                                                               les\@angular\tsc-wrapped\src\main.js:26:15)
    at Object.<anonymous> (D:\jscode\a2-go\node_modules\@angular\compiler-cli\sr                                                               c\main.js:14:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
Compilation failed

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                               node_modules\\npm\\bin\\npm-cli.js" "run" "aot"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! angular2-go@0.0.1 aot: `ngc -p tsconfig-aot.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-go@0.0.1 aot script 'ngc -p tsconfig-aot.json'.
npm ERR! This is most likely a problem with the angular2-go package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ngc -p tsconfig-aot.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-go
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular2-go
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\jscode\a2-go\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                               node_modules\\npm\\bin\\npm-cli.js" "run" "start-aot"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! angular2-go@0.0.1 start-aot: `npm run aot && npm run rollup && gulp cop                                                               y-aot && npm run lite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-go@0.0.1 start-aot script 'npm run aot && npm ru                                                               n rollup && gulp copy-aot && npm run lite'.
npm ERR! This is most likely a problem with the angular2-go package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run aot && npm run rollup && gulp copy-aot && npm run lite
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-go
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular2-go
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\jscode\a2-go\npm-debug.log

**Comment by finalxcode** [comment]
+1 

E:\project_test\Angular-aot-demo>npm run build:aot && npm run lite:aot

> angular-quickstart@1.0.0 build:aot E:\project_test\Angular-aot-demo
> ngc -p tsconfig-aot.json && rollup -c rollup-config.js

Error: Error at E:/project_test/Angular-aot-demo/app/main-aot.ts:1:1: File 'E:/project_test/Angular-aot-demo/typings/globals/core-js/index.d.ts' not found.
    at check (E:\project_test\Angular-aot-demo\node_modules\@angular\tsc-wrapped\src\tsc.js:31:15)
    at Tsc.typeCheck (E:\project_test\Angular-aot-demo\node_modules\@angular\tsc-wrapped\src\tsc.js:86:9)
    at E:\project_test\Angular-aot-demo\node_modules\@angular\tsc-wrapped\src\main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Compilation failed
